<?php

namespace Xpressengine\Plugins\ChartWidget\Widgets;

use XeFrontend;
use Xpressengine\Widget\AbstractWidget;
use Xpressengine\Plugins\ChartWidget\Plugin;

class Widget extends AbstractWidget
{

    protected static $seq = 0;

    /**
     * Get the evaluated contents of the object.
     *
     * @return string
     */
    public function render()
    {
        $setting = $this->setting();

        $seq = static::$seq++;

        return $this->renderSkin(compact('setting', 'seq'));
    }

    public function renderSetting(array $args = [])
    {
        return view(Plugin::view('views.widget.setting'), compact('args'));
    }

    public function resolveSetting(array $inputs = [])
    {
        return parent::resolveSetting($inputs); // TODO: Change the autogenerated stub
    }


}