<?php

namespace Xpressengine\Plugins\ChartWidget\Widgets;

use XeFrontend;
use Xpressengine\Widget\AbstractWidget;
use Xpressengine\Plugins\ChartWidget\Plugin;

class Widget extends AbstractWidget
{

    /**
     * Get the evaluated contents of the object.
     *
     * @return string
     */
    public function render()
    {

    }

    public function renderSetting(array $args = [])
    {
        return view(Plugin::view('views.widget.setting'));
    }

    public function resolveSetting(array $inputs = [])
    {
        return parent::resolveSetting($inputs); // TODO: Change the autogenerated stub
    }
}